site_name: User-agent Reference Registry
site_description: Public references for user-agent organized by OS, Software, and hardware.
site_url: https://wildforcer.github.io/ua-registry
repo_url: https://github.com/wildforcer/ua-registry
repo_name: GitHub

theme:
  name: readthedocs

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - meta
  - toc:
      toc_depth: 1

extra_css:
  - ./stylesheets/extra.css